// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI / migrations use a DIRECT (non-pooled) connection when one is
    // provided — advisory locks used by `migrate deploy` don't work over a
    // PgBouncer pooler (e.g. Neon's -pooler host). The app runtime still uses
    // the pooled DATABASE_URL (see src/lib/db.ts). Falls back to DATABASE_URL
    // for local/dev where there's no separate direct URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
